/**
 * Schema of the JSON artifacts generated by scripts/preprocess.ts into
 * public/data. These types are the single contract shared between the
 * preprocessing pipeline (Node) and the Next.js frontend (browser).
 *
 * Field names on the very high-frequency JourneyPoint type are deliberately
 * short (`t,x,z,mx,my`) to keep the per-match JSON small — there are ~73k
 * journey points across the dataset.
 */

/* --------------------------------- events -------------------------------- */

/** The 8 raw event strings present in the `event` column. */
export type EventName =
  | "Position"
  | "BotPosition"
  | "Kill"
  | "Killed"
  | "BotKill"
  | "BotKilled"
  | "KilledByStorm"
  | "Loot";

/** Discrete (non-movement) events grouped for markers, filters and heatmaps. */
export type EventCategory = "kill" | "death" | "storm" | "loot";

/** Maps each discrete event name to its category. Position/BotPosition are
 *  movement samples and become journey points, not discrete events. */
export const EVENT_CATEGORY: Record<string, EventCategory> = {
  Kill: "kill",
  BotKill: "kill",
  Killed: "death",
  BotKilled: "death",
  KilledByStorm: "storm",
  Loot: "loot",
};

export const EVENT_CATEGORIES: EventCategory[] = ["kill", "death", "storm", "loot"];

/** Pre-aggregated, map-wide heatmap layers. */
export type HeatmapKind = "traffic" | "kills" | "deaths" | "loot";
export const HEATMAP_KINDS: HeatmapKind[] = ["traffic", "kills", "deaths", "loot"];

/* -------------------------------- manifest -------------------------------- */

export interface WorldBoundsJSON {
  minX: number;
  maxX: number;
  minZ: number;
  maxZ: number;
}

export interface MapManifest {
  id: string;
  name: string;
  blurb: string;
  /** Public path to the resized minimap, e.g. /maps/AmbroseValley.webp */
  imageUrl: string;
  imageWidth: number;
  imageHeight: number;
  scale: number;
  originX: number;
  originZ: number;
  worldBounds: WorldBoundsJSON;
  coordinateNotes: string;
  matchCount: number;
  /** Total telemetry rows recorded on this map across all matches. */
  sampleCount: number;
}

export interface MatchSummary {
  matchId: string;
  /** Path under public/data to the full match file, e.g. matches/<slug>.json */
  file: string;
  mapId: string;
  date: string; // ISO yyyy-mm-dd
  /** Wall-clock epoch milliseconds (derived from the epoch-seconds `ts`). */
  startTime: number;
  endTime: number;
  durationSeconds: number;
  playerCount: number; // human tracks
  botCount: number; // bot tracks
  pointCount: number; // total journey points across all tracks
  eventCounts: Record<EventCategory, number>;
  totalEvents: number; // total discrete events
  /** Ranking score used to surface the richest matches first. */
  activityScore: number;
}

export interface DataManifest {
  generatedAt: string;
  dataset: string;
  maps: MapManifest[];
  dates: string[];
  /** All matches, sorted by activityScore descending. */
  matches: MatchSummary[];
  eventTypes: EventName[];
  heatmapKinds: HeatmapKind[];
  totals: {
    files: number;
    rows: number;
    matches: number;
    humanPlayers: number;
    bots: number;
    journeyPoints: number;
    discreteEvents: number;
  };
  /** A good first selection for the UI: the single richest match. */
  defaults: { mapId: string; date: string; matchId: string };
}

/* ------------------------------ per-match data ---------------------------- */

/** One sampled position on a player's path. */
export interface JourneyPoint {
  /** Seconds elapsed from match start. */
  t: number;
  /** World coordinates (horizontal plane). */
  x: number;
  z: number;
  /** Minimap image pixel coordinates, in [0, imageSize]. */
  mx: number;
  my: number;
}

export interface PlayerTrack {
  playerId: string;
  isBot: boolean;
  /** Short display label, e.g. "Human 0019c5" or "Bot 1388". */
  label: string;
  /** First/last point times (seconds from match start). */
  firstT: number;
  lastT: number;
  points: JourneyPoint[];
}

export interface GameEvent {
  /** Unique within the match. */
  id: string;
  event: EventName;
  category: EventCategory;
  t: number; // seconds from match start
  x: number;
  z: number;
  mx: number;
  my: number;
  /** The owner of the file this event came from (always a human in practice). */
  playerId: string;
  isBot: boolean;
}

export interface MatchData {
  matchId: string;
  mapId: string;
  date: string;
  startTime: number;
  endTime: number;
  durationSeconds: number;
  players: PlayerTrack[];
  events: GameEvent[];
}

/* -------------------------------- heatmaps -------------------------------- */

export interface HeatmapGrid {
  mapId: string;
  kind: HeatmapKind;
  /** Number of cells per side (square grid over the minimap image). */
  grid: number;
  /** Pixel size of one cell in image space. */
  cellSize: number;
  /** Highest single-cell count — denominator for 0..1 normalization. */
  max: number;
  /** Total samples binned into the grid. */
  total: number;
  /** Sparse non-zero cells as flattened triples: [col, row, count, ...]. */
  cells: number[];
}

/* -------------------------------- insights -------------------------------- */

/** One data-backed observation produced by scripts/generate-insights.ts. */
export interface Insight {
  id: number;
  title: string;
  caughtMyEye: string;
  evidence: string[];
  recommendation: string;
  metricsAffected: string[];
  whyItMatters: string;
}

export interface InsightsReport {
  generatedAt: string;
  insights: Insight[];
  /** Supporting raw numbers, for transparency. */
  stats: Record<string, number | string>;
}
